version: '3.8'

networks:
  default:

services:

  # mysql-container:
  #   image: mysql:8.2.0
  #   ports:
  #     - "3307:3306"
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=123456
  #     - MYSQL_DATABASE=FreelancerMarketplaceUser
  #   networks:
  #     - default

  freelancer-marketplace-user:
    # image: your-nest-app-image
    ports:
      - "3334:3334"
    build:
      dockerfile: Dockerfile  # Reference the Dockerfile
      context: .
    # depends_on:
    #   - mysql-container
    environment:
      - DATABASE_HOST=mysql-container
      - DATABASE_PORT=3306
      - DATABASE_USERNAME=admin-user-service
      - DATABASE_PASSWORD=123456
      - DATABASE_NAME=FreelancerMarketplaceUser
    networks:
      - default

  
